/*
 * To change this license header, choose License Headers in Project Properties.
 *+ To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.openiptools;

import java.util.Arrays;

/**
 *
 * @author jaime
 */
public class ipcalc extends javax.swing.JFrame {
    
    /**
     * Creates new form ipcalc
     */
    public ipcalc() {
        initComponents();
        resulN1.setText("Aguardando Inserção de dados...");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ipTxt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        maskTx1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resulN1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        resulN2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LOGO_Experimental Project");

        ipTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ipTxt1MouseClicked(evt);
            }
        });
        ipTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipTxt1ActionPerformed(evt);
            }
        });

        jLabel2.setText("IP:");

        maskTx1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                maskTx1FocusGained(evt);
            }
        });

        jLabel3.setText("Mask:");

        resulN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resulN1.setText("jLabel4");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        resulN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resulN2.setText("jLabel4;");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resulN2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resulN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ipTxt1)
                    .addComponent(maskTx1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maskTx1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addComponent(resulN1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resulN2)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ipTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipTxt1ActionPerformed
            
        //EXCLUIR!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! teste
        // TODO add your handling code here:
    }//GEN-LAST:event_ipTxt1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(ipTxt1.getText().contains(".")){
            
            String[] treated = {ipTxt1.getText(), maskTx1.getText()};
            treated = Treatment.input(treated);
            String[] ipv4 = Core.input(treated); 
            resulN1.setText(ipv4[0]);
            resulN2.setText(ipv4[1]);
            //ip[i] = Integer.parseInt(ipTxt1.getText().substring(a,b)); //coloca condiçao para auto preenchimento com 0
        }
        else{
        resulN1.setText("Erro Ex:192.168.000.100");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ipTxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipTxt1MouseClicked
        // TODO add your handling code here:
        resulN1.setText("Ex 192.168.1.0");
    }//GEN-LAST:event_ipTxt1MouseClicked

    private void maskTx1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_maskTx1FocusGained
        // TODO add your handling code here:
        resulN1.setText("Mask 255.255.*.* or /24");
    }//GEN-LAST:event_maskTx1FocusGained
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ipcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ipcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ipcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ipcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ipcalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ipTxt1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField maskTx1;
    private javax.swing.JLabel resulN1;
    private javax.swing.JLabel resulN2;
    // End of variables declaration//GEN-END:variables
}
